## docker-compose.yaml
version: '3.6'
services:
  graphql-engine:
    container_name: '__SUPABASE_PROJECT_NAME__-hasura'
    image: hasura/graphql-engine:v2.9.0
    network_mode: host
    restart: always # if fail (REASON - OOM or etc) restart always
    env_file:
      - .env